name: learnsphere

on:
  push:
    branches: ["main"]

jobs:
  learnsphere-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: LearnSphere
          MYSQL_ROOT_PASSWORD: root_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.3.9"
          extensions: mbstring, xml, curl, zip, gd, bcmath, sqlite3, mysqli, pdo_mysql, fileinfo

      - uses: actions/checkout@v4

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer u

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 775 storage bootstrap/cache

      - name: Wait for MySQL to be ready
        run: |
          for i in {60..0}; do
            if mysql -h 127.0.0.1 -u root -proot_password -e "SELECT 1"; then
              echo "MySQL is ready!"
              break
            fi
            echo 'Waiting for MySQL...'
            sleep 5
          done

      - name: Test MySQL Connection
        run: |
          mysql -h 127.0.0.1 -u root -proot_password -e "SHOW DATABASES;"

      - name: Execute migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: LearnSphere
          DB_USERNAME: root
          DB_PASSWORD: root_password
        run: php artisan migrate --force

      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: LearnSphere
          DB_USERNAME: root
          DB_PASSWORD: root_password
        run: php artisan test
